title: Silei Huo # your name (or website title) here
logo: "/images/myphoto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-driven problem solver with extensive finance industry experience across strategic planning, business intelligence and digital transformation. MBA from London Business School. 
  <br><br>
  Data Science | Banking | FinTech | Payment Processing 
  <br><br>
  <a href="https://www.linkedin.com/in/silei-huo/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-T72L4DZTPS # your Google Analytics tracking ID here
