title: Sandra (Silei) Huo # your name (or website title) here
logo: "/images/myphoto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-driven problem solver with extensive experience in Banking and Technology (Payments), focusing on Strategic Planning, Business Intelligence (BI), and Data Analytics. MBA from London Business School. 
  <br><br>
  Data Science | FinTech | Payment Processing | Banking
  <br><br>
  <a href="https://www.linkedin.com/in/silei-huo/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-T72L4DZTPS # your Google Analytics tracking ID here
